### ISSUE TITLE
We still can't see any release of vabase for 2017

### ISSUE THREAD

**Issue by forestbat** [tunnelvisionlabs/vsbase#63]
@sharwell https://marketplace.visualstudio.com/items?itemName=SamHarwell.JavaLanguageSupport#overview
You probably should update this。

**Comment by sharwell** [comment]
The linked extension is actually part of this repository:
https://github.com/tunnelvisionlabs/JavaForVS

This is specifically a duplicate of tunnelvisionlabs/JavaForVS#47 😄
